# Generated by Django 3.1.8 on 2021-05-10 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='collect_day',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='is_suspended',
            field=models.BooleanField(default=None, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='special_day',
            field=models.DateField(default=None, verbose_name=datetime.datetime),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
