# Generated by Django 3.1.8 on 2021-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
