# Generated by Django 3.1.8 on 2021-05-07 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='special_day',
            field=models.DateField(default=None, verbose_name=datetime.datetime),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
