# Generated by Django 3.1.8 on 2021-05-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210507_1252'),
        ('customers', '0003_auto_20210507_1125'),
    ]

    operations = [
    ]
