# Generated by Django 3.1.8 on 2021-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_merge_20210507_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='cust_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
