# Generated by Django 3.1.8 on 2021-05-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210507_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_suspended',
            field=models.BooleanField(default=None, verbose_name=False),
            preserve_default=False,
        ),
    ]
