# Generated by Django 3.1.8 on 2021-05-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_is_suspended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='collect_day',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
