<<<<<<< HEAD
# Generated by Django 3.1.8 on 2021-05-07 19:46
=======
# Generated by Django 3.1.8 on 2021-05-07 19:51
>>>>>>> 8a3ed4f257f00751769a060f209cabb9ab73cf7b

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=50)),
=======
                ('emp_name', models.CharField(max_length=50)),
                ('pickup_day', models.DateField(verbose_name=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])),
>>>>>>> 8a3ed4f257f00751769a060f209cabb9ab73cf7b
            ],
        ),
    ]
