# Generated by Django 3.1.8 on 2021-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_pickup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='zipcode',
            field=models.IntegerField(default=None),
        ),
    ]
